apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: churro
    pipeline: somepipeline
  name: churrodata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: "hostpath"
