apiVersion: v1
kind: Service
metadata:
  labels:
    app: churro
  name: memsql-studio
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: memsql-studio
  sessionAffinity: None
  type: ClusterIP
