apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: churro-ui
rules:
- apiGroups:
  - churro.project.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - namespaces
  verbs:
  - list
  - get
  - create
