// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package extract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExtractClient is the client API for Extract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtractClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type extractClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractClient(cc grpc.ClientConnInterface) ExtractClient {
	return &extractClient{cc}
}

func (c *extractClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/extract.Extract/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractServer is the server API for Extract service.
// All implementations should embed UnimplementedExtractServer
// for forward compatibility
type ExtractServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedExtractServer should be embedded to have forward compatible implementations.
type UnimplementedExtractServer struct {
}

func (UnimplementedExtractServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

// UnsafeExtractServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractServer will
// result in compilation errors.
type UnsafeExtractServer interface {
	mustEmbedUnimplementedExtractServer()
}

func RegisterExtractServer(s grpc.ServiceRegistrar, srv ExtractServer) {
	s.RegisterService(&Extract_ServiceDesc, srv)
}

func _Extract_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extract.Extract/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Extract_ServiceDesc is the grpc.ServiceDesc for Extract service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Extract_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extract.Extract",
	HandlerType: (*ExtractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Extract_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/extract/extract.proto",
}
