FROM golang:1.16 as builder
ADD . /build
ADD ./ui/main.go /build
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -o churro-ui


FROM fedora:latest

# Copy our static executable
COPY --from=builder /build/churro-ui /usr/local/bin
#RUN yum -y install sqlite
RUN mkdir /pages
COPY certs/ui/ /
COPY pages/ /pages
COPY static/ /static

# Run the churro-operator binary.
WORKDIR /
ENTRYPOINT ["/usr/local/bin/churro-ui"]
