FROM golang:1.16 as builder
ADD . /build
ADD ./cmd/churro-extract/churro-extract.go /build
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -o churro-extract

FROM fedora:latest

# Copy our static executable
COPY --from=builder /build/churro-extract /usr/local/bin

# Run the churro-extract binary.
ENTRYPOINT ["/usr/local/bin/churro-extract"]
