FROM fedora:latest

RUN yum -y install yum-utils
RUN yum-config-manager --add-repo https://release.memsql.com/production/rpm/x86_64/repodata/memsql.repo
RUN yum -y install singlestoredb-studio

EXPOSE 8080/tcp
# Run the churro-operator binary.
ENTRYPOINT ["/usr/bin/singlestoredb-studio"]
