apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: churro
  name: churro-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: churro-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: churro-operator
        name: churro-operator
    spec:
      containers:
      - image: churrodata/churro-operator:latest
        imagePullPolicy: IfNotPresent
        name: churro-operator
        volumeMounts:
        - name: templatesdir
          mountPath: /templates
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: CHURRO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CHURRO_PULL_SECRET_NAME
          value: regcred
      restartPolicy: Always
      serviceAccount: churro-operator
      serviceAccountName: churro-operator
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: templatesdir
        configMap:
          name: churro-templates
