apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  generation: 1
  labels:
    app: mysql-operator
    controller-tools.k8s.io: "1.0"
    manager: kube-apiserver
    operation: Update
  name: mysqlbackups.mysql.presslabs.org
spec:
  conversion:
    strategy: None
  group: mysql.presslabs.org
  names:
    kind: MysqlBackup
    listKind: MysqlBackupList
    plural: mysqlbackups
    singular: mysqlbackup
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
