// Code generated by controller-gen. DO NOT EDIT.

package uiv1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Churroui) DeepCopyInto(out *Churroui) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Churroui.
func (in *Churroui) DeepCopy() *Churroui {
	if in == nil {
		return nil
	}
	out := new(Churroui)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Churroui) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChurrouiList) DeepCopyInto(out *ChurrouiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Churroui, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChurrouiList.
func (in *ChurrouiList) DeepCopy() *ChurrouiList {
	if in == nil {
		return nil
	}
	out := new(ChurrouiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChurrouiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChurrouiSpec) DeepCopyInto(out *ChurrouiSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChurrouiSpec.
func (in *ChurrouiSpec) DeepCopy() *ChurrouiSpec {
	if in == nil {
		return nil
	}
	out := new(ChurrouiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChurrouiStatus) DeepCopyInto(out *ChurrouiStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChurrouiStatus.
func (in *ChurrouiStatus) DeepCopy() *ChurrouiStatus {
	if in == nil {
		return nil
	}
	out := new(ChurrouiStatus)
	in.DeepCopyInto(out)
	return out
}
